path: '/home/vant/data/graph_data/pdb_poses/het_4PP9CHEMBL1288582_0_traj_pdb/'
output: "/home/vant/data/gnn_data/output/trial/"
target: '/home/vant/data/graph_data/target2_lig1/4PP9CHEMBL1288582_target.csv'

ligand_name: 'LIG'
selection_radius: 20
center: 'geometric'
decay_function: 'expo'
nodes: 'atoms'

fitting: 'GNN'

batch_size: 32
learning_rate: 0.01
epochs: 400
