path: '/home/vant/data/'
output: "/home/vant/data/"
run: 'try'
ligand_name: 'LIG'
selection_radius: 20
center: 'geometric'
decay_function: 'expo'
nodes: 'atoms'

batch_size: 32
learning_rate: 0.01
epochs: 400
